name: Build .NET Framework 4.8 Console App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v6

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build app
        run: >
          msbuild
          optimizerNXT.slnx
          /t:Build
          /p:Configuration=Release
          /p:Platform=Any CPU
          /p:Optimize=true
          /p:Prefer32Bit=false
          /m
