name: Build and release OptimizerNXT

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build app
        run: >
          msbuild
          optimizerNXT.slnx
          /t:Build
          /p:Configuration=Release
          /p:Platform="Any CPU"
          /p:Optimize=true
          /p:Prefer32Bit=false
          /p:DebugType=none
          /m

      - name: Create release with tag
        uses: ncipollo/release-action@v1
        with:
          tag: v0.0.1
          name: Release v0.0.1
          body: Automated build release
          files: "./optimizerNXT/bin/Release/optimizerNXT.exe"
